# Generated by Django 4.0.5 on 2022-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledcontactform',
            name='message_saved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
