# Generated by Django 4.0.5 on 2022-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0002_filledcontactform_message_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledcontactform',
            name='subject',
            field=models.CharField(default='', max_length=128),
        ),
    ]
