# Generated by Django 4.0.5 on 2022-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0003_filledcontactform_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'Active Cs'), (2, 'Avtive 3D'), (3, 'Preview Cs'), (4, 'Preview 3D')])),
                ('the_file', models.FileField(upload_to='')),
            ],
        ),
    ]
