# Generated by Django 4.0.5 on 2022-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0005_alter_documents_the_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='the_file',
            field=models.FileField(upload_to='./media/documents'),
        ),
    ]
