# Generated by Django 4.0.5 on 2022-08-08 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_ssg', '0006_alter_documents_the_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('users', models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
