# Generated by Django 4.0.5 on 2022-08-08 20:39

import datetime
from django.db import migrations, models
import simple_ssg.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0007_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='the_file',
            field=models.FileField(default=datetime.datetime(2022, 8, 8, 20, 39, 49, 855374), upload_to=simple_ssg.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='the_file',
            field=models.FileField(upload_to='./documents'),
        ),
    ]
