# Generated by Django 4.0.5 on 2022-08-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0008_files_the_file_alter_documents_the_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
