# Generated by Django 4.0.5 on 2022-08-08 22:46

from django.db import migrations, models
import simple_ssg.models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0009_files_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='the_file',
            field=models.FileField(blank=True, null=True, upload_to=simple_ssg.models.user_directory_path),
        ),
    ]
