# Generated by Django 4.0.5 on 2022-08-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0011_remove_files_name_remove_files_users_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='titfile_namele',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
