# Generated by Django 4.0.5 on 2022-08-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_ssg', '0012_files_titfile_namele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='titfile_namele',
            new_name='file_name',
        ),
    ]
